import re
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack13")