import re
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack13")
print("hijack14")
print("hijack15")
print("hijack16")
print("hijack17")
print("hijack17")