import re
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack")
print("hijack13")
print("hijack14")